/**
 * Property-Based Tests for Spot Popup Content Equivalence
 *
 * **Feature: liquid-rendering-optimization, Property 7: Spot popup content equivalence**
 * **Validates: Requirements 6.2**
 *
 * Property: For any spot data object (with name, slug, type, rejected status,
 * description, address, paddle craft types, and coordinates), the popup HTML
 * generated by detail-map.js (via PaddelbuchSpotPopup) shall be identical to
 * the popup HTML that the original inline spot layout JavaScript would have generated.
 */

const fc = require('fast-check');

// ---------------------------------------------------------------------------
// Load the spot-popup module (external JS under test)
// ---------------------------------------------------------------------------

// Provide a minimal DOM environment for escapeHtml
if (typeof document === 'undefined') {
  const { JSDOM } = require('jsdom');
  const dom = new JSDOM('<!DOCTYPE html><html><body></body></html>');
  global.document = dom.window.document;
  global.window = dom.window;
}

require('../../assets/js/spot-popup.js');

const SpotPopup = window.PaddelbuchSpotPopup;

// ---------------------------------------------------------------------------
// Reference implementation: "original inline code" popup generation
//
// The original inline Liquid templates built popup HTML directly in the
// layout file using Liquid interpolation. This reference mirrors that
// original behavior exactly, using the same HTML structure, escaping,
// and label logic that the Liquid template produced.
// ---------------------------------------------------------------------------

// Same icon mappings as spot-popup.js (originally hardcoded in the Liquid template)
const ICON_BASE_PATH = '/assets/images/icons/';
const SPOT_TYPE_ICONS = {
  'einstieg-ausstieg': 'entryexit',
  'nur-einstieg': 'entry',
  'nur-ausstieg': 'exit',
  'rasthalte': 'rest',
  'notauswasserungsstelle': 'emergency'
};

const SPOT_TYPE_NAMES = {
  'einstieg-ausstieg': { de: 'Ein- und Ausstieg', en: 'Entry and Exit' },
  'nur-einstieg': { de: 'Nur Einstieg', en: 'Entry Only' },
  'nur-ausstieg': { de: 'Nur Ausstieg', en: 'Exit Only' },
  'rasthalte': { de: 'Rasthalte', en: 'Rest Stop' },
  'notauswasserungsstelle': { de: 'Notauswasserungsstelle', en: 'Emergency Landing' }
};

const PADDLE_CRAFT_TYPE_NAMES = {
  'seekajak': { de: 'Seekajak', en: 'Sea Kayak' },
  'kanadier': { de: 'Kanadier', en: 'Canoe' },
  'stand-up-paddle-board': { de: 'Stand Up Paddle Board (SUP)', en: 'Stand Up Paddle Board (SUP)' }
};

/**
 * Reference escapeHtml — uses the same DOM-based approach as spot-popup.js
 */
function refEscapeHtml(text) {
  if (!text) return '';
  var div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

function refStripHtml(html) {
  if (!html) return '';
  return html.replace(/<[^>]*>/g, '');
}

function refTruncate(text, maxLength) {
  if (!text) return '';
  if (text.length <= maxLength) return text;
  return text.substring(0, maxLength) + '...';
}

function refGetIconPath(spotTypeSlug, isRejected, variant) {
  variant = variant || 'light';
  var iconName = 'entryexit';
  if (isRejected) {
    iconName = 'noentry';
  } else if (spotTypeSlug && Object.prototype.hasOwnProperty.call(SPOT_TYPE_ICONS, spotTypeSlug)) {
    iconName = SPOT_TYPE_ICONS[spotTypeSlug];
  }
  return ICON_BASE_PATH + iconName + '-' + variant + '.svg';
}

function refGetLabels(locale) {
  if (locale === 'en') {
    return {
      gps: 'GPS',
      approxAddress: 'Approx. Address',
      type: 'Type',
      potentiallyUsableBy: 'Potentially Usable By',
      copy: 'Copy',
      copyGps: 'Copy GPS to clipboard',
      copyAddress: 'Copy approx. address to clipboard',
      navigate: 'Navigate To',
      moreDetails: 'More details'
    };
  }
  return {
    gps: 'GPS',
    approxAddress: 'Ungefähre Adresse',
    type: 'Typ',
    potentiallyUsableBy: 'Potenziell nutzbar f\u00fcr',
    copy: 'Kopieren',
    copyGps: 'GPS in der Zwischenablage kopieren',
    copyAddress: 'Ungefähre Adresse in der Zwischenablage kopieren',
    navigate: 'Navigieren zu',
    moreDetails: 'Weitere Details'
  };
}


/**
 * Reference implementation of generateSpotPopupContent — mirrors the original
 * inline Liquid template popup HTML generation. This is what the original
 * spot.html layout's inline <script> block would have produced.
 */
function refGenerateSpotPopupContent(spot, locale) {
  locale = locale || 'de';
  var labels = refGetLabels(locale);
  var localePrefix = (locale !== 'de') ? '/' + locale : '';
  var html = [];

  var isRejected = spot.rejected === true || spot.rejected === 'true';
  var spotTypeSlug = spot.spotType_slug || spot.spotTypeSlug || spot.spot_type_slug;
  var iconPath = refGetIconPath(spotTypeSlug, isRejected, 'light');

  var spotTypeLabel = spotTypeSlug;
  if (spotTypeSlug && Object.prototype.hasOwnProperty.call(SPOT_TYPE_NAMES, spotTypeSlug)) {
    spotTypeLabel = SPOT_TYPE_NAMES[spotTypeSlug][locale] || SPOT_TYPE_NAMES[spotTypeSlug]['de'] || spotTypeSlug;
  }

  html.push('<div class="popup-icon-div">');
  html.push('<span class="popup-icon"><img src="' + iconPath + '" alt="" width="20" height="20" loading="lazy" /></span>');
  html.push(refEscapeHtml(spotTypeLabel));
  html.push('</div>');

  html.push('<span class="popup-title"><h1>' + refEscapeHtml(spot.name) + '</h1></span>');

  var description = spot.description || spot.description_excerpt;
  if (description) {
    var plainText = refStripHtml(description);
    var excerpt = refTruncate(plainText, 150);
    if (excerpt) {
      html.push('<div><p>' + refEscapeHtml(excerpt) + '</p></div>');
    }
  }

  html.push('<table class="popup-details-table"><tbody>');

  if (spot.paddleCraftTypes && spot.paddleCraftTypes.length > 0) {
    html.push('<tr><th>' + labels.potentiallyUsableBy + ':</th><td colspan="2"><ul>');
    for (var i = 0; i < spot.paddleCraftTypes.length; i++) {
      var craftSlug = spot.paddleCraftTypes[i];
      var craftName = craftSlug;
      if (Object.prototype.hasOwnProperty.call(PADDLE_CRAFT_TYPE_NAMES, craftSlug)) {
        craftName = PADDLE_CRAFT_TYPE_NAMES[craftSlug][locale] || PADDLE_CRAFT_TYPE_NAMES[craftSlug]['de'] || craftSlug;
      }
      html.push('<li>' + refEscapeHtml(craftName) + '</li>');
    }
    html.push('</ul></td></tr>');
  }

  var lat = spot.location ? (spot.location.lat || spot.location.latitude) : null;
  var lon = spot.location ? (spot.location.lon || spot.location.lng || spot.location.longitude) : null;

  if (lat !== null && lon !== null) {
    html.push('<tr><th>' + labels.gps + ':</th>');
    html.push('<td>' + lat + ', ' + lon + '</td>');
    html.push('<td class="clipboard-cell-popup">');
    html.push('<button title="' + labels.copyGps + '" type="button" class="popup-btn" ');
    html.push('onclick="PaddelbuchClipboard.copyGPS(\'' + lat + '\', \'' + lon + '\', this)">');
    html.push(labels.copy + '</button></td></tr>');
  }

  if (spot.approximateAddress) {
    var escapedAddress = refEscapeHtml(spot.approximateAddress).replace(/'/g, "\\'");
    html.push('<tr><th>' + labels.approxAddress + ':</th>');
    html.push('<td>' + refEscapeHtml(spot.approximateAddress) + '</td>');
    html.push('<td class="clipboard-cell-popup">');
    html.push('<button title="' + labels.copyAddress + '" type="button" class="popup-btn" ');
    html.push('onclick="PaddelbuchClipboard.copyAddress(\'' + escapedAddress + '\', this)">');
    html.push(labels.copy + '</button></td></tr>');
  }

  html.push('</tbody></table>');

  if (lat !== null && lon !== null) {
    html.push('<button type="button" class="popup-btn">');
    html.push('<a href="https://www.google.com/maps/dir/?api=1&destination=' + lat + ',' + lon + '" ');
    html.push('target="_blank" rel="noopener noreferrer">' + labels.navigate + '</a></button>');
  }

  if (spot.slug) {
    html.push('<button class="popup-btn popup-btn-right">');
    html.push('<a href="' + localePrefix + '/einstiegsorte/' + refEscapeHtml(spot.slug) + '/">');
    html.push(labels.moreDetails + '</a></button>');
  }

  return html.join('');
}

/**
 * Reference implementation of generateRejectedSpotPopupContent.
 */
function refGenerateRejectedSpotPopupContent(spot, locale) {
  locale = locale || 'de';
  var labels = refGetLabels(locale);
  var localePrefix = (locale !== 'de') ? '/' + locale : '';
  var html = [];

  var iconPath = refGetIconPath(null, true, 'light');
  var noEntryLabel = (locale === 'en') ? 'No Entry Spot' : 'Kein Zutritt Ort';
  var iconAlt = (locale === 'en') ? 'No entry spot icon' : 'Kein Zutritt Symbol';

  html.push('<div class="popup-icon-div">');
  html.push('<span class="popup-icon">');
  html.push('<img src="' + iconPath + '" alt="' + iconAlt + '" height="20" width="20" loading="lazy" />');
  html.push('</span>');
  html.push(refEscapeHtml(noEntryLabel));
  html.push('</div>');

  html.push('<span class="popup-title"><h1>' + refEscapeHtml(spot.name) + '</h1></span>');

  var description = spot.description || spot.description_excerpt;
  if (description) {
    var plainText = refStripHtml(description);
    html.push('<div><p>' + refEscapeHtml(plainText) + '</p></div>');
  }

  if (spot.slug) {
    html.push('<button class="popup-btn popup-btn-right">');
    html.push('<a href="' + localePrefix + '/einstiegsorte/' + refEscapeHtml(spot.slug) + '/">');
    html.push(labels.moreDetails + '</a></button>');
  }

  return html.join('');
}

// ---------------------------------------------------------------------------
// Arbitraries — smart generators for valid spot data
// ---------------------------------------------------------------------------

const VALID_SPOT_TYPES = [
  'einstieg-ausstieg',
  'nur-einstieg',
  'nur-ausstieg',
  'rasthalte',
  'notauswasserungsstelle'
];

const VALID_PADDLE_CRAFT_TYPES = [
  'seekajak',
  'kanadier',
  'stand-up-paddle-board'
];

/** Locale arbitrary. */
const localeArb = fc.constantFrom('de', 'en');

/** Spot type slug arbitrary. */
const spotTypeArb = fc.constantFrom(...VALID_SPOT_TYPES);

/** Paddle craft type arbitrary. */
const paddleCraftTypeArb = fc.constantFrom(...VALID_PADDLE_CRAFT_TYPES);

/** Latitude in valid Swiss range. */
const latArb = fc.double({ min: 45.8, max: 47.8, noNaN: true, noDefaultInfinity: true });

/** Longitude in valid Swiss range. */
const lonArb = fc.double({ min: 5.9, max: 10.5, noNaN: true, noDefaultInfinity: true });

/** Safe string that avoids characters which break HTML structure in test comparison. */
const safeStringArb = fc.stringOf(
  fc.constantFrom(
    'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p',
    'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P',
    '0','1','2','3','4','5','6','7','8','9',
    ' ','-','.',',','!','?',':',';','(',')'
  ),
  { minLength: 1, maxLength: 60 }
).filter(s => s.trim().length > 0);

/** Generates a slug-like string. */
const slugArb = fc.stringOf(
  fc.constantFrom('a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','0','1','2','3','-'),
  { minLength: 1, maxLength: 30 }
).filter(s => /^[a-z0-9]/.test(s) && s.trim().length > 0);

/** Generates a location object. */
const locationArb = fc.record({
  lat: latArb,
  lon: lonArb
});

/** Generates a full spot data object for normal (non-rejected) spots. */
const normalSpotArb = fc.record({
  name: safeStringArb,
  slug: slugArb,
  spotType_slug: spotTypeArb,
  rejected: fc.constant(false),
  description: fc.oneof(
    fc.constant(null),
    fc.constant(''),
    safeStringArb,
    safeStringArb.map(s => '<p>' + s + '</p>')
  ),
  approximateAddress: fc.oneof(fc.constant(null), fc.constant(''), safeStringArb),
  paddleCraftTypes: fc.array(paddleCraftTypeArb, { minLength: 0, maxLength: 3 }),
  location: fc.oneof(fc.constant(null), locationArb)
});

/** Generates a full spot data object for rejected spots. */
const rejectedSpotArb = fc.record({
  name: safeStringArb,
  slug: slugArb,
  spotType_slug: spotTypeArb,
  rejected: fc.constant(true),
  description: fc.oneof(fc.constant(null), fc.constant(''), safeStringArb),
  approximateAddress: fc.constant(null),
  paddleCraftTypes: fc.constant([]),
  location: fc.oneof(fc.constant(null), locationArb)
});

/** Generates any spot data object (normal or rejected). */
const anySpotArb = fc.oneof(normalSpotArb, rejectedSpotArb);

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('Spot Popup Content Equivalence — Property 7', () => {

  describe('normal (non-rejected) spots', () => {
    test('external JS popup HTML matches original inline code for any spot data', () => {
      fc.assert(
        fc.property(normalSpotArb, localeArb, (spot, locale) => {
          var externalHtml = SpotPopup.generateSpotPopupContent(spot, locale);
          var referenceHtml = refGenerateSpotPopupContent(spot, locale);

          return externalHtml === referenceHtml;
        }),
        { numRuns: 100 }
      );
    });

    test('popup contains spot name for any spot', () => {
      fc.assert(
        fc.property(normalSpotArb, localeArb, (spot, locale) => {
          var html = SpotPopup.generateSpotPopupContent(spot, locale);
          return html.includes(refEscapeHtml(spot.name));
        }),
        { numRuns: 100 }
      );
    });

    test('popup contains correct locale prefix in details link', () => {
      fc.assert(
        fc.property(normalSpotArb, localeArb, (spot, locale) => {
          var html = SpotPopup.generateSpotPopupContent(spot, locale);
          var expectedPrefix = (locale !== 'de') ? '/' + locale : '';
          var expectedLink = expectedPrefix + '/einstiegsorte/' + refEscapeHtml(spot.slug) + '/';
          return html.includes(expectedLink);
        }),
        { numRuns: 100 }
      );
    });

    test('popup contains GPS coordinates when location present', () => {
      fc.assert(
        fc.property(
          normalSpotArb.filter(s => s.location !== null),
          localeArb,
          (spot, locale) => {
            var html = SpotPopup.generateSpotPopupContent(spot, locale);
            return html.includes(String(spot.location.lat)) &&
                   html.includes(String(spot.location.lon));
          }
        ),
        { numRuns: 100 }
      );
    });

    test('popup contains paddle craft type names when present', () => {
      fc.assert(
        fc.property(
          normalSpotArb.filter(s => s.paddleCraftTypes.length > 0),
          localeArb,
          (spot, locale) => {
            var html = SpotPopup.generateSpotPopupContent(spot, locale);
            return spot.paddleCraftTypes.every(craftSlug => {
              var expectedName = craftSlug;
              if (Object.prototype.hasOwnProperty.call(PADDLE_CRAFT_TYPE_NAMES, craftSlug)) {
                expectedName = PADDLE_CRAFT_TYPE_NAMES[craftSlug][locale] ||
                               PADDLE_CRAFT_TYPE_NAMES[craftSlug]['de'] || craftSlug;
              }
              return html.includes(refEscapeHtml(expectedName));
            });
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('rejected spots', () => {
    test('external JS rejected popup HTML matches original inline code for any rejected spot', () => {
      fc.assert(
        fc.property(rejectedSpotArb, localeArb, (spot, locale) => {
          var externalHtml = SpotPopup.generateRejectedSpotPopupContent(spot, locale);
          var referenceHtml = refGenerateRejectedSpotPopupContent(spot, locale);

          return externalHtml === referenceHtml;
        }),
        { numRuns: 100 }
      );
    });

    test('rejected popup contains no-entry icon', () => {
      fc.assert(
        fc.property(rejectedSpotArb, localeArb, (spot, locale) => {
          var html = SpotPopup.generateRejectedSpotPopupContent(spot, locale);
          return html.includes('noentry-light.svg');
        }),
        { numRuns: 100 }
      );
    });

    test('rejected popup contains correct locale-specific label', () => {
      fc.assert(
        fc.property(rejectedSpotArb, localeArb, (spot, locale) => {
          var html = SpotPopup.generateRejectedSpotPopupContent(spot, locale);
          if (locale === 'en') {
            return html.includes('No Entry Spot');
          }
          return html.includes('Kein Zutritt Ort');
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('detail-map.js popup dispatch equivalence', () => {
    test('for any spot, the correct popup function is called based on rejected status', () => {
      fc.assert(
        fc.property(anySpotArb, localeArb, (spot, locale) => {
          var isRejected = spot.rejected === true || spot.rejected === 'true';

          var externalHtml;
          if (isRejected) {
            externalHtml = SpotPopup.generateRejectedSpotPopupContent(spot, locale);
          } else {
            externalHtml = SpotPopup.generateSpotPopupContent(spot, locale);
          }

          var referenceHtml;
          if (isRejected) {
            referenceHtml = refGenerateRejectedSpotPopupContent(spot, locale);
          } else {
            referenceHtml = refGenerateSpotPopupContent(spot, locale);
          }

          return externalHtml === referenceHtml;
        }),
        { numRuns: 100 }
      );
    });
  });

  describe('icon path equivalence', () => {
    test('icon path from external JS matches reference for any spot type and rejected status', () => {
      fc.assert(
        fc.property(
          spotTypeArb,
          fc.boolean(),
          (spotType, isRejected) => {
            var externalPath = SpotPopup.getIconPath(spotType, isRejected, 'light');
            var referencePath = refGetIconPath(spotType, isRejected, 'light');
            return externalPath === referencePath;
          }
        ),
        { numRuns: 100 }
      );
    });
  });

  describe('label equivalence', () => {
    test('labels from external JS match reference for any locale', () => {
      fc.assert(
        fc.property(localeArb, (locale) => {
          var externalLabels = SpotPopup.getLabels(locale);
          var referenceLabels = refGetLabels(locale);

          return Object.keys(referenceLabels).every(key =>
            externalLabels[key] === referenceLabels[key]
          );
        }),
        { numRuns: 100 }
      );
    });
  });
});
