# frozen_string_literal: true

# Handles two favicon concerns:
#
# 1. Copies the SVG favicon to /favicon.ico so automatic browser requests
#    to /favicon.ico are served instead of returning a 404.
#
# 2. Registers the Apple Touch Icon PNG (generated by
#    _scripts/generate_apple_touch_icon.py) as /apple-touch-icon.png
#    at the site root, where iOS devices expect to find it.

module Paddelbuch
  class FaviconGenerator < Jekyll::Generator
    safe true
    priority :low

    SVG_SOURCE = "assets/images/logo-favicon.svg"
    TOUCH_ICON_SOURCE = "assets/images/apple-touch-icon.png"

    def generate(site)
      svg_path = File.join(site.source, SVG_SOURCE)
      touch_path = File.join(site.source, TOUCH_ICON_SOURCE)

      if File.exist?(svg_path)
        site.static_files << AliasedStaticFile.new(site, svg_path, "favicon.ico")
      end

      if File.exist?(touch_path)
        site.static_files << AliasedStaticFile.new(site, touch_path, "apple-touch-icon.png")
      else
        Jekyll.logger.warn "Favicon:", "Apple Touch Icon not found at #{TOUCH_ICON_SOURCE}. " \
          "Run: python3 _scripts/generate_apple_touch_icon.py"
      end
    end
  end

  class AliasedStaticFile < Jekyll::StaticFile
    def initialize(site, source_path, dest_name)
      @source_path = source_path
      @dest_name = dest_name
      super(site, site.source, "", dest_name)
    end

    def path
      @source_path
    end

    def destination(dest)
      File.join(dest, @dest_name)
    end
  end
end
